// Flat config. `next lint` and a bare `eslint .` both read this.
//
// eslint-config-next is still eslintrc-shaped, so it comes in through
// FlatCompat. Keep this file small: the point of adding lint here is to make
// CI able to fail on NEW problems, not to relitigate style across the
// existing ~8k lines.
import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

const config = [
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "dist/**",
      "build/**",
      "model/**",
      "data/**",
      "analysis/**",
      "catboost_info/**",
      // Generated by `next dev`/`next build` -- not ours to lint.
      "next-env.d.ts",
      // Separate projects with their own toolchains.
      "apps/**",
      "services/**",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    rules: {
      // Downgraded, not disabled. There are 5 pre-existing `any`s in
      // components/LeafletMap.tsx (~L329-352). Making them errors would put
      // CI in the red on its first run, which is how lint gates get turned
      // off. Burn them down, then promote this back to "error".
      "@typescript-eslint/no-explicit-any": "warn",
    },
  },
];

export default config;
